-- Table: public.Admins

-- DROP TABLE IF EXISTS public."Admins";

CREATE TABLE IF NOT EXISTS public."Admins"
(
    "Email" character varying(250) COLLATE pg_catalog."default" NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1 ),
    "PasswordHash" character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Admins_pkey" PRIMARY KEY ("Id")
);



ALTER TABLE IF EXISTS public."Admins"
    OWNER to postgres;