﻿CREATE TABLE IF NOT EXISTS public."Orders"
(
    "Email" character varying(250) ,
    "Phone" character varying(20),
    "Date" timestamp without time zone,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1 ),
    CONSTRAINT "Orders_pkey" PRIMARY KEY ("Id")
)

ALTER TABLE IF EXISTS public."Orders"
    OWNER to postgres;